name: check rust code
on: [push]
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bevy build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: Built release binaries (x86)
          path: target/release/
  build_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bevy build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --all-features
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bevy build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: fmt
          args: --check
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bevy build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bevy build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev zip gzip tar
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: ructions/cargo@v1
        with:
          command: doc
          args: --all-features
      - name: Zip Docs
        run: |
          pwd
          ls -la
          ls -la target
          cd target ; zip -r documentation.zip doc/
      - name: tar Docs
        run: |
          pwd
          cd target ; tar -zcvf documentation.tar.gz doc/
      - uses: actions/upload-artifact@v4
        with:
          name: generated-documentation-zipped
          path: documentation.zip
      - uses: actions/upload-artifact@v4
        with:
          name: generated-documentation-tgz
          path: documentation.tar.gz
